// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/services": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/contacts": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/admin/posts": {
    params: {};
  };
  "/admin/media": {
    params: {};
  };
  "/admin/messages": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/auth/signup": {
    params: {};
  };
  "/auth/signin": {
    params: {};
  };
  "/auth/signout": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/services" | "/projects" | "/blog" | "/contacts" | "/admin" | "/admin/posts" | "/admin/media" | "/admin/messages" | "/admin/settings" | "/auth/signup" | "/auth/signin" | "/auth/signout";
  };
  "routes/public/layout.tsx": {
    id: "routes/public/layout";
    page: "/" | "/about" | "/services" | "/projects" | "/blog" | "/contacts";
  };
  "routes/public/home.tsx": {
    id: "routes/public/home";
    page: "/";
  };
  "routes/public/about.tsx": {
    id: "routes/public/about";
    page: "/about";
  };
  "routes/public/services.tsx": {
    id: "routes/public/services";
    page: "/services";
  };
  "routes/public/projects.tsx": {
    id: "routes/public/projects";
    page: "/projects";
  };
  "routes/public/blog.tsx": {
    id: "routes/public/blog";
    page: "/blog";
  };
  "routes/public/contacts.tsx": {
    id: "routes/public/contacts";
    page: "/contacts";
  };
  "routes/admin/layout.tsx": {
    id: "routes/admin/layout";
    page: "/admin" | "/admin/posts" | "/admin/media" | "/admin/messages" | "/admin/settings";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin";
  };
  "routes/admin/posts.tsx": {
    id: "routes/admin/posts";
    page: "/admin/posts";
  };
  "routes/admin/media.tsx": {
    id: "routes/admin/media";
    page: "/admin/media";
  };
  "routes/admin/messages.tsx": {
    id: "routes/admin/messages";
    page: "/admin/messages";
  };
  "routes/admin/settings.tsx": {
    id: "routes/admin/settings";
    page: "/admin/settings";
  };
  "routes/auth/signup.tsx": {
    id: "routes/auth/signup";
    page: "/auth/signup";
  };
  "routes/auth/signin.tsx": {
    id: "routes/auth/signin";
    page: "/auth/signin";
  };
  "routes/auth/signout.tsx": {
    id: "routes/auth/signout";
    page: "/auth/signout";
  };
};